// <auto-generated />
namespace StockManage.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview7-19363-02")]
    public sealed partial class Product22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product22));
        
        string IMigrationMetadata.Id
        {
            get { return "201908211217234_Product22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
